baseURL = 'https://madhurtoppo.github.io'
languageCode = 'en-us'
title = 'Madhur Toppo'
theme = 'PaperMod'

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search"
weight = 50

[params]
showToc = true
TocOpen = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideMeta = false
env = "production"
hideDescriptionInList = false

  [params.profileMode]
  enabled = true
  title = "Madhur Toppo"
  subtitle = "Hi 👋! I'm Madhur, I am a skilled Senior Software Engineer with over nine years of experience in developing complex software solutions in e-commerce, finance sectors and startups. My expertise includes designing backend systems, creating APIs and UIs, implementing design patterns, applying Devops best practices, building apps end-to-end and leading teams. I have a strong proficiency in Java, Spring, Typescript, Node.js, React, Docker, Kubernetes, Microservices, APIs, Databases, AWS, Cloud and other related technologies."
  imageUrl = "home/me.jpg"
  imageWidth = 220
  imageHeight = 220

  [params.cover]
  hiddenInList = false
  hiddenInSingle = false

  [[params.socialIcons]]
  name = "email"
  url = "mailto:madhur.toppo@gmail.com"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/madhurtoppo"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/madhurtoppo"

  [[params.socialIcons]]
  name = "cv"
  url = "https://drive.google.com/file/d/1-piii_DmqT6x2k_Hmyzog9LZD1habNzD/view"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true
